all:
  children:
    ha_cluster:
      vars:
        ansible_user: fuse2003
        ansible_python_interpreter: /usr/bin/python3
        ansible_become: true
        ansible_become_method: sudo
      hosts:
        lb1:
          ansible_host: 192.168.1.32
          keepalived_role: MASTER
          keepalived_priority: 101
        lb2:
          ansible_host: 192.168.1.32
          keepalived_role: BACKUP
          keepalived_priority: 100
